Alias: $event-type = https://oversight-on-fhir.org/fhir/CodeSystem/oversight-event-type
Alias: $disposition = https://oversight-on-fhir.org/fhir/CodeSystem/oversight-disposition
Alias: $high-risk = https://oversight-on-fhir.org/fhir/CodeSystem/high-risk-rule
Alias: $dataop = http://terminology.hl7.org/CodeSystem/v3-DataOperation
Alias: $prov-type = http://terminology.hl7.org/CodeSystem/provenance-participant-type

// The AI system as a Device
Instance: oversight-ai
InstanceOf: Device
Usage: #example
Title: "Oversight-on-FHIR AI Device"
* status = #active
* deviceName.name = "Oversight-on-FHIR agent (claude-opus-4-8)"
* deviceName.type = #model-name
* version.value = "0.1.0"

// The recommendation carrier
Instance: gr-example
InstanceOf: DeescalationGuidanceResponse
Usage: #example
Title: "Example De-escalation Guidance Response"
* status = #success
* moduleUri = "https://oversight-on-fhir.org/fhir/module/deescalation"
* subject = Reference(Patient/clean-1)
* occurrenceDateTime = "2026-07-10T12:00:00Z"
* performer = Reference(Device/oversight-ai)
* note.text = "This recommendation was generated by an AI system and requires clinician review."

// AI authorship of that recommendation
Instance: prov-example
InstanceOf: AIAuthorshipProvenance
Usage: #example
Title: "Example AI Authorship Provenance"
* target = Reference(GuidanceResponse/gr-example)
* recorded = "2026-07-10T12:00:00Z"
* activity = $dataop#CREATE "create"
* activity.text = "machine-generated"
* agent.type = $prov-type#author
* agent.who = Reference(Device/oversight-ai)

// A clinician rejecting the recommendation, reason: data-vintage
Instance: oversight-reject-example
InstanceOf: OversightEvent
Usage: #example
Title: "Example Oversight Event — Reject (data-vintage)"
* extension[reason].valueCodeableConcept = OversightReason#data-vintage
* type = $event-type#oversight-decision
* subtype = $disposition#reject
* action = #R
* recorded = "2026-07-10T12:05:00Z"
* outcome = #0
* agent.who = Reference(Practitioner/dr-alice)
* agent.requestor = true
* source.observer.display = "Oversight-on-FHIR"
* entity.what = Reference(GuidanceResponse/gr-example)
* entity.detail.type = "reason-note"
* entity.detail.valueString = "Repeat culture from today shows a resistant isolate."

// A system escalation over a high-risk recommendation
Instance: escalation-example
InstanceOf: OversightEvent
Usage: #example
Title: "Example Oversight Event — Escalation (allergy_to_candidate)"
* type = $event-type#escalation
* subtype = $high-risk#allergy_to_candidate
* action = #E
* recorded = "2026-07-10T12:10:00Z"
* outcome = #0
* agent.who.display = "Oversight-on-FHIR routing engine"
* agent.requestor = false
* source.observer.display = "Oversight-on-FHIR"
* entity.what = Reference(GuidanceResponse/gr-example)
