import copy

import pytest

from oversight.errors import SchemaValidationError
from oversight.schema.validate import load_schema, validate_recommendation

VALID = {
    "schema_version": "0.1.0",
    "patient_reference": "Patient/clean-1",
    "encounter_reference": "Encounter/enc-1",
    "candidacy": {
        "is_deescalation_candidate": "yes",
        "current_regimen": [{"medication": "piperacillin-tazobactam", "fhir_reference": "MedicationRequest/mr-1"}],
        "recommended_action": "narrow",
        "recommended_agent": "cefazolin",
        "recommended_dose": None,
    },
    "rationale": [
        {"assertion": "Isolate is MSSA susceptible to cefazolin.",
         "evidence": [{"type": "fhir_resource", "fhir_reference": "DiagnosticReport/dr-1",
                       "document_reference": None, "text_span": None, "knowledge_source_id": None}]}
    ],
    "deterministic_tool_result": None,
    "confidence": {"score": 0.9, "method": "self_consistency", "rationale": "3/3 agree"},
    "routing": {"decision": "surface", "triggered_high_risk_rules": [], "below_confidence_threshold": False},
    "disclosure_text": "This recommendation was generated by an AI system.",
}


def test_valid_recommendation_passes():
    validate_recommendation(VALID)  # must not raise


def test_schema_id_and_version():
    schema = load_schema()
    assert schema["properties"]["schema_version"]["const"] == "0.1.0"


def test_rationale_without_evidence_is_rejected():
    bad = copy.deepcopy(VALID)
    bad["rationale"][0]["evidence"] = []
    with pytest.raises(SchemaValidationError):
        validate_recommendation(bad)


def test_empty_rationale_is_rejected():
    bad = copy.deepcopy(VALID)
    bad["rationale"] = []
    with pytest.raises(SchemaValidationError):
        validate_recommendation(bad)


def test_model_authored_dose_is_rejected():
    bad = copy.deepcopy(VALID)
    bad["candidacy"]["recommended_dose"] = "500 mg q8h"
    with pytest.raises(SchemaValidationError):
        validate_recommendation(bad)
