import copy

import httpx
import pytest

from oversight.config import Settings
from oversight.fhir.client import FhirClient
from oversight.oversight.service import OversightService

SURFACE_REC = {"schema_version": "0.1.0", "patient_reference": "Patient/clean-1",
               "encounter_reference": "Encounter/enc-clean-1",
               "stewardship_assessment": "MSSA susceptible to cefazolin; recommend de-escalation.",
               "candidacy": {"is_deescalation_candidate": "yes",
                   "current_regimen": [{"medication": "piperacillin-tazobactam", "fhir_reference": "MedicationRequest/mr-clean-1"}],
                   "recommended_action": "narrow", "recommended_agent": "cefazolin", "recommended_dose": None},
               "rationale": [{"assertion": "MSSA susceptible to cefazolin.",
                   "evidence": [{"type": "fhir_resource", "fhir_reference": "DiagnosticReport/dr-clean-1",
                                 "document_reference": None, "text_span": None, "knowledge_source_id": None}]}],
               "deterministic_tool_result": None,
               "confidence": {"score": 1.0, "method": "self_consistency", "rationale": "3/3"},
               "routing": {"decision": "surface", "triggered_high_risk_rules": [], "below_confidence_threshold": False},
               "disclosure_text": "This recommendation was generated by an AI system."}
ESCALATE_REC = {**copy.deepcopy(SURFACE_REC), "patient_reference": "Patient/hr-1",
                "encounter_reference": "Encounter/enc-hr-1",
                "routing": {"decision": "escalate", "triggered_high_risk_rules": ["allergy_to_candidate"],
                            "below_confidence_threshold": False}}


def _hapi_up(base):
    try:
        return httpx.get(f"{base}/metadata", timeout=3).status_code == 200
    except Exception:
        return False


settings = Settings()
pytestmark = pytest.mark.skipif(not _hapi_up(settings.fhir_base_url), reason="HAPI not running")


def _svc():
    return OversightService(FhirClient.from_settings(settings), model="claude-opus-4-8",
                            version="0.1.0", backend="frontier")


def test_persist_and_capture_are_retrievable_over_rest():
    svc = _svc()
    refs = svc.persist_recommendation(copy.deepcopy(SURFACE_REC))
    gr_ref = refs["guidance_response"]
    svc.capture_disposition(gr_ref, "Practitioner/dr-alice", disposition="reject",
                            reason_code="data-vintage", note="Newer culture back.")

    client = httpx.Client(base_url=settings.fhir_base_url, timeout=10)
    prov = client.get(f"/Provenance?target={gr_ref}").json()
    assert prov.get("total", 0) >= 1
    audit = client.get(f"/AuditEvent?entity={gr_ref}").json()
    codes = [e["resource"]["type"]["code"] for e in audit.get("entry", [])]
    assert "oversight-decision" in codes


def test_escalation_recommendation_records_escalation_event():
    svc = _svc()
    refs = svc.persist_recommendation(copy.deepcopy(ESCALATE_REC))
    gr_ref = refs["guidance_response"]
    client = httpx.Client(base_url=settings.fhir_base_url, timeout=10)
    audit = client.get(f"/AuditEvent?entity={gr_ref}").json()
    types = [e["resource"]["type"]["code"] for e in audit.get("entry", [])]
    assert "escalation" in types
