import copy

from oversight.inference.base import InferenceResult

_CANNED = {
    "schema_version": "0.1.0",
    "patient_reference": "Patient/stub", "encounter_reference": "Encounter/stub",
    "candidacy": {"is_deescalation_candidate": "insufficient_information",
                  "current_regimen": [{"medication": "piperacillin-tazobactam", "fhir_reference": "MedicationRequest/stub"}],
                  "recommended_action": "insufficient_information", "recommended_agent": None, "recommended_dose": None},
    "rationale": [{"assertion": "Local stub backend: canned response for seam demonstration only.",
                   "evidence": [{"type": "knowledge_passage", "fhir_reference": None, "document_reference": None,
                                 "text_span": None, "knowledge_source_id": "stub"}]}],
    "deterministic_tool_result": None,
    "confidence": {"score": 0.0, "method": "stub", "rationale": "Local stub returns fixed output."},
    "routing": {"decision": "escalate", "triggered_high_risk_rules": [], "below_confidence_threshold": True},
    "disclosure_text": "This recommendation was generated by an AI system (local stub backend).",
}


class LocalModelBackend:
    """On-prem open-weight backend seam (Section 13). This build ships a stub that proves the
    config swap is code-free; real constrained-decoding inference attaches here later without
    changing the interface."""

    def __init__(self, model: str = "qwen3-4b-stub"):
        self.model = model
        self.name = f"local:{model}"

    def generate(self, prompt: str, schema: dict, n_samples: int = 1) -> InferenceResult:
        samples = [copy.deepcopy(_CANNED) for _ in range(max(1, n_samples))]
        return InferenceResult(recommendation=copy.deepcopy(_CANNED), samples=samples,
                               raw_meta={"backend": self.name, "model": self.model, "stub": True})
