import json

from oversight.inference.base import InferenceResult

# Narrow-spectrum de-escalation targets, in order of preference (narrowest first).
NARROW_PRIORITY = ["cefazolin", "ceftriaxone"]


def _extract_context(prompt: str) -> dict | None:
    """Parse the CLINICAL CONTEXT JSON that build_prompt embeds in the prompt."""
    marker = "CLINICAL CONTEXT (from FHIR):"
    if marker not in prompt:
        return None
    block = prompt.split(marker, 1)[1].split("KNOWLEDGE PASSAGES", 1)[0].strip()
    try:
        return json.loads(block)
    except json.JSONDecodeError:
        pass
    try:  # brace-match fallback
        start = block.index("{")
        depth = 0
        for i, ch in enumerate(block[start:], start):
            depth += (ch == "{") - (ch == "}")
            if depth == 0:
                return json.loads(block[start:i + 1])
    except (ValueError, json.JSONDecodeError):
        return None
    return None


def _propose(context: dict) -> dict:
    pref = context.get("patient_reference", "Patient/unknown")
    eref = context.get("encounter_reference", "Encounter/unknown")
    regimen = context.get("current_regimen", []) or []
    suscepts = context.get("susceptibilities", []) or []
    conclusions = context.get("culture_conclusions", []) or []

    susceptible = {s["agent"].lower(): s.get("fhir_reference")
                   for s in suscepts if str(s.get("interpretation", "")).lower().startswith("suscept")}
    target = next((a for a in NARROW_PRIORITY if a in susceptible), None)
    culture_ref = conclusions[0].get("fhir_reference") if conclusions else None

    rec = {
        "schema_version": "0.1.0", "patient_reference": pref, "encounter_reference": eref,
        "stewardship_assessment": "",
        "candidacy": {"is_deescalation_candidate": "yes", "current_regimen": regimen,
                      "recommended_action": "narrow", "recommended_agent": None, "recommended_dose": None},
        "rationale": [], "deterministic_tool_result": None,
        "confidence": {"score": 0.0, "method": "placeholder", "rationale": ""},
        "routing": {"decision": "surface", "triggered_high_risk_rules": [], "below_confidence_threshold": False},
        "disclosure_text": "This recommendation was generated by an AI system and requires clinician review.",
    }

    if target:
        rec["stewardship_assessment"] = (
            f"Culture and susceptibilities support de-escalating from broad-spectrum empiric therapy to "
            f"{target}, the narrowest agent that covers the isolate. No contraindication to narrowing is "
            f"evident from the available data. Recommend narrowing; clinician to confirm timing and duration.")
        rec["candidacy"]["recommended_agent"] = target
        ev_ref = susceptible.get(target) or culture_ref
        rec["rationale"] = [
            {"assertion": f"Culture and susceptibilities support narrowing to {target}.",
             "evidence": [{"type": "fhir_resource", "fhir_reference": ev_ref,
                           "document_reference": None, "text_span": None, "knowledge_source_id": None}]},
            {"assertion": f"Institutional antibiogram supports {target} as a narrow-spectrum choice once susceptibility is confirmed.",
             "evidence": [{"type": "knowledge_passage", "fhir_reference": None, "document_reference": None,
                           "text_span": None, "knowledge_source_id": "antibiogram#staphylococcus-aureus-mssa"}]},
        ]
    elif suscepts:
        rec["stewardship_assessment"] = (
            "Culture has resulted but the organism requires continued coverage with the current agent; "
            "no narrower susceptible target is appropriate (e.g. antipseudomonal coverage). Recommend "
            "continuing current therapy, reassessing daily, and setting a definite stop date.")
        rec["candidacy"]["is_deescalation_candidate"] = "no"
        rec["candidacy"]["recommended_action"] = "continue"
        rec["rationale"] = [
            {"assertion": "Culture resulted but no narrower susceptible agent is appropriate; continue current therapy.",
             "evidence": [{"type": "fhir_resource", "fhir_reference": culture_ref,
                           "document_reference": None, "text_span": None, "knowledge_source_id": None}]
             if culture_ref else
             [{"type": "knowledge_passage", "fhir_reference": None, "document_reference": None,
               "text_span": None, "knowledge_source_id": "antibiogram#pseudomonas-aeruginosa"}]},
        ]
    else:
        rec["stewardship_assessment"] = (
            "Susceptibility results are not yet available, so there is insufficient information to safely "
            "narrow therapy. Recommend continuing empiric therapy pending cultures and reassessing at the "
            "next antibiotic time-out; if cultures remain negative and infection becomes unlikely, consider "
            "stopping therapy.")
        rec["candidacy"]["is_deescalation_candidate"] = "insufficient_information"
        rec["candidacy"]["recommended_action"] = "insufficient_information"
        rec["rationale"] = [
            {"assertion": "No susceptibility results are available; there is insufficient information to narrow therapy.",
             "evidence": [{"type": "knowledge_passage", "fhir_reference": None, "document_reference": None,
                           "text_span": None, "knowledge_source_id": "formulary#de-escalation-policy"}]},
        ]
    return rec


class ScriptedDemoBackend:
    """Offline, deterministic backend for the recorded demo. Reads the FHIR-derived clinical context
    from the prompt and proposes de-escalation the way the real model would — so the whole census
    works with no API key. The orchestrator's deterministic tool + routing still run on top."""

    name = "demo:scripted"

    def generate(self, prompt: str, schema: dict, n_samples: int = 1) -> InferenceResult:
        context = _extract_context(prompt) or {}
        rec = _propose(context)
        import copy
        samples = [copy.deepcopy(rec) for _ in range(max(1, n_samples))]
        return InferenceResult(recommendation=copy.deepcopy(rec), samples=samples,
                               raw_meta={"backend": self.name, "scripted": True})
