import copy
import re

from oversight.inference.base import InferenceResult

# Per-patient curated model *proposals*. The deterministic tool and routing engine still run on
# top of these, so the high-risk patient genuinely escalates — only the model's proposal is scripted.
# This backend exists so the recorded demo runs fully offline and deterministically (Section 7).

_NARROW_CEFAZOLIN = {
    "schema_version": "0.1.0",
    "candidacy": {"is_deescalation_candidate": "yes",
        "current_regimen": [{"medication": "piperacillin-tazobactam", "fhir_reference": None}],
        "recommended_action": "narrow", "recommended_agent": "cefazolin", "recommended_dose": None},
    "rationale": [
        {"assertion": "Blood culture grew MSSA susceptible to cefazolin, supporting de-escalation from piperacillin-tazobactam.",
         "evidence": [{"type": "fhir_resource", "fhir_reference": None,
                       "document_reference": None, "text_span": None, "knowledge_source_id": None}]},
        {"assertion": "Institutional antibiogram names cefazolin the preferred narrow-spectrum agent for MSSA bacteremia.",
         "evidence": [{"type": "knowledge_passage", "fhir_reference": None, "document_reference": None,
                       "text_span": None, "knowledge_source_id": "antibiogram#staphylococcus-aureus-mssa"}]},
    ],
    "deterministic_tool_result": None,
    "confidence": {"score": 0.0, "method": "placeholder", "rationale": ""},
    "routing": {"decision": "surface", "triggered_high_risk_rules": [], "below_confidence_threshold": False},
    "disclosure_text": "This recommendation was generated by an AI system and requires clinician review.",
}

# patient id -> (encounter ref, medication request ref, diagnostic report ref)
_PATIENTS = {
    "clean-1": ("Encounter/enc-clean-1", "MedicationRequest/mr-clean-1", "DiagnosticReport/dr-clean-1"),
    "hr-1": ("Encounter/enc-hr-1", "MedicationRequest/mr-hr-1", "DiagnosticReport/dr-hr-1"),
}


def _rec_for(patient_id: str) -> dict:
    enc, mr, dr = _PATIENTS[patient_id]
    rec = copy.deepcopy(_NARROW_CEFAZOLIN)
    rec["patient_reference"] = f"Patient/{patient_id}"
    rec["encounter_reference"] = enc
    rec["candidacy"]["current_regimen"][0]["fhir_reference"] = mr
    rec["rationale"][0]["evidence"][0]["fhir_reference"] = dr
    return rec


class ScriptedDemoBackend:
    """Offline, deterministic backend for the recorded demo. Detects the patient from the prompt
    and returns a curated proposal; the orchestrator's deterministic tool + routing still run."""

    name = "demo:scripted"

    def generate(self, prompt: str, schema: dict, n_samples: int = 1) -> InferenceResult:
        patient_id = None
        m = re.search(r"Patient/([A-Za-z0-9\-]+)", prompt)
        if m and m.group(1) in _PATIENTS:
            patient_id = m.group(1)
        if patient_id is None:
            # Unknown patient: honestly report insufficiency rather than guess.
            rec = copy.deepcopy(_NARROW_CEFAZOLIN)
            rec["patient_reference"] = "Patient/unknown"
            rec["encounter_reference"] = "Encounter/unknown"
            rec["candidacy"]["is_deescalation_candidate"] = "insufficient_information"
            rec["candidacy"]["recommended_action"] = "insufficient_information"
            rec["candidacy"]["recommended_agent"] = None
            rec["candidacy"]["current_regimen"] = []  # no resolvable MedicationRequest ref for unknown patient
        else:
            rec = _rec_for(patient_id)
        samples = [copy.deepcopy(rec) for _ in range(max(1, n_samples))]
        return InferenceResult(recommendation=copy.deepcopy(rec), samples=samples,
                               raw_meta={"backend": self.name, "scripted": True})
