"""Scripted demo: persist a recommendation, capture a clinician rejection, print the GuidanceResponse id
so the independent client can reconstruct the story. Synthetic data only."""
import sys

from oversight.config import Settings
from oversight.fhir.client import FhirClient
from oversight.oversight.service import OversightService

REC = {"schema_version": "0.1.0", "patient_reference": "Patient/clean-1",
       "encounter_reference": "Encounter/enc-clean-1",
       "stewardship_assessment": "MSSA bacteremia susceptible to cefazolin; recommend de-escalation from piperacillin-tazobactam.",
       "candidacy": {"is_deescalation_candidate": "yes",
           "current_regimen": [{"medication": "piperacillin-tazobactam", "fhir_reference": "MedicationRequest/mr-clean-1"}],
           "recommended_action": "narrow", "recommended_agent": "cefazolin", "recommended_dose": None},
       "rationale": [{"assertion": "MSSA susceptible to cefazolin.",
           "evidence": [{"type": "fhir_resource", "fhir_reference": "DiagnosticReport/dr-clean-1",
                         "document_reference": None, "text_span": None, "knowledge_source_id": None}]}],
       "deterministic_tool_result": None,
       "confidence": {"score": 1.0, "method": "self_consistency", "rationale": "3/3 agree"},
       "routing": {"decision": "surface", "triggered_high_risk_rules": [], "below_confidence_threshold": False},
       "disclosure_text": "This recommendation was generated by an AI system and requires clinician review."}


def main() -> int:
    settings = Settings()
    svc = OversightService(FhirClient.from_settings(settings), model=settings.model,
                           version="0.1.0", backend=settings.backend)
    refs = svc.persist_recommendation(REC)
    gr_ref = refs["guidance_response"]
    svc.capture_disposition(gr_ref, "Practitioner/dr-alice", disposition="reject",
                            reason_code="data-vintage", note="Repeat culture from today shows a resistant isolate.")
    gr_id = gr_ref.split("/", 1)[1]
    print(f"Persisted {gr_ref}, Provenance, and an OversightEvent (reject / data-vintage).")
    print(f"\nReconstruct independently with:\n  uv run python scripts/independent_client.py {gr_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
